### ISSUE TITLE
failure to setup

### ISSUE THREAD

**Issue by barislav** [drohm/pi-sht1x#1]
Hi,

I'm very new to all this so please forgive me.
I'm trying to use a SHT71 humidity sensor with a R.Pi 2 b
The R.Pi is new so may not have everything needed to support the setup.

I copied the pi-sht1x-1.0.6 to my R.Pi and now wish to install it.
Up until now when i'm installing things on the R.Pi i have done the following:

pi@raspberrypi~/pi-sht1x-1.0.6 $ sudo python setup.py install

Howerver when i do this i get:

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    with open(path.join(here, 'README.rst'), encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function

Or if i try:
pi@raspberrypi~ $ pip3 install pi-sht1x even with sudo i get:

 bash: pip3:command not found

i would greatly appreciate your help.

**Comment by drohm** [comment]
Do you have python 3 installed?  Try running:

```
python3
```

to see if python 3 launches. If it doesn't, install python 3 with:

```
sudo apt-get install python3
```

and install pip3:

```
sudo apt-get install python3-pip
```

Doug

**Comment by drohm** [comment]
Also, after you get python3 and pip3 installed, use the second method of installing pi-sht1x:

```
pip3 install pi-sht1x
```

Doug

**Comment by barislav** [comment]
Hi Doug,
Thanks for your prompt reply.
Python3 was installed and I've now installed pip3.
When I enter:
pip3 install pi-sht1x
I receive an error saying no such file or directory README.rst

**Comment by drohm** [comment]
I've made a fix and uploaded a new version to PyPI - 1.0.8.  Try doing the install again using the same command, which will pull the latest version.  Let me know if that clears up the error.

**Comment by barislav** [comment]
The install worked this time thank you.
This is my full code for to the program:
Under the program is the error message i recieve when i run the program.
I appreciate all your help, anymore pointers would be greatly apreciated.
Kind regards.

from time import sleep
import RPi.GPIO as GPIO
from pi_sht1x import SHT1x

DATA_PIN = 18  ## physical pin 12
SCK_PIN = 23 ## physical pin 16

with SHT1x(DATA_PIN, SCK_PIN, gpio_mode=GPIO.BCM) as sensor:
    temp = sensor.read_temperature()
    humidity = sensor.read_humidity(temp)
    print(sensor)

ERROR MSG:
pi@raspberrypi ~/examples $ sudo python3 humidity.py
Traceback (most recent call last):
  File "humidity.py", line 8, in <module>
    with SHT1x(DATA_PIN, SCK_PIN, gpio_mode=GPIO.BOARD) as sensor:
  File "/usr/local/lib/python3.2/dist-packages/pi_sht1x/sht1x.py", line 78, in **init**
    self.initialize_sensor()
  File "/usr/local/lib/python3.2/dist-packages/pi_sht1x/sht1x.py", line 157, in initialize_sensor
    self._write_status_register(mask)
  File "/usr/local/lib/python3.2/dist-packages/pi_sht1x/sht1x.py", line 454, in _write_status_register
    self._send_command(measurement=False)
  File "/usr/local/lib/python3.2/dist-packages/pi_sht1x/sht1x.py", line 254, in _send_command
    self._get_ack(command_name)
  File "/usr/local/lib/python3.2/dist-packages/pi_sht1x/sht1x.py", line 397, in _get_ack
    raise SHT1xError(message)
pi_sht1x.sht1x.SHT1xError: SHT1x failed to properly receive command [['WriteStatusRegister'] - 00000110]

**Comment by drohm** [comment]
Double-check your pin connections.  The error indicates that its not communicating with the sensor properly.  Are you using 3.3V or 5V to power the sensor?

![raspberry-pi-b -gpio-pinouts](https://cloud.githubusercontent.com/assets/184959/7376782/26e48554-edb0-11e4-9cd9-d0196abe4c00.png)

Could you also check the log file?  Do this:

```
ls -al /usr/local/lib/python3.2/dist-packages/pi_sht1x
```

you should see a file called `pi_sht1x.log`  If you can, please paste the contents here.

**Comment by drohm** [comment]
I just realized that in your initial post, you mentioned you're using the SHT71 sensor.  I don't believe that sensor will work with this library.  This library was specifically written to work with the SHT1x sensors (SHT10, SHT11, and SHT15).  I'm not sure how compatible the SHT71 is to this series, I'd have to look at the data sheet.  Most likely it isn't.

**Comment by barislav** [comment]
Ah yes sorry, I didn't realise that. Thanks for pointing that out. I'll purchase a SHT1x sensor if this doesn't work out.

May i also ask if my interpret is correct in that the BCM pin 18 is equal to the physical pin 12 etc..

Thanks again for your help. 

For the record this is the contents of the pi_sht1x.log

[2015-02-17 19:42:08,612]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 19:42:08,613]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 19:42:08,614]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 19:42:08,615]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 19:42:08,616]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 19:42:08,617]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 19:42:08,617]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 19:42:08,618]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 19:42:08,619]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x76a13e18>
[2015-02-17 19:42:58,090]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 19:42:58,093]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 19:42:58,095]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 19:42:58,097]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 19:42:58,099]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 19:42:58,101]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 19:42:58,103]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 19:42:58,104]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 19:42:58,106]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x7695fe18>
[2015-02-17 19:54:12,845]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 19:54:12,848]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 19:54:12,849]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 19:54:12,850]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 19:54:12,851]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 19:54:12,852]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 19:54:12,853]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 19:54:12,853]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 19:54:12,854]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x7693adc8>
[2015-02-17 19:55:11,645]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 19:55:11,647]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 19:55:11,648]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 19:55:11,649]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 19:55:11,649]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 19:55:11,650]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 19:55:11,651]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 19:55:11,652]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 19:55:11,652]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x76936dc8>
[2015-02-17 20:07:22,897]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 20:07:22,899]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 20:07:22,900]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 20:07:22,900]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 20:07:22,901]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 20:07:22,902]        sht1x:    **exit**:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 20:07:22,902]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'NameError'>
name 'temp' is not defined
<traceback object at 0x76a0ed00>
[2015-02-17 20:07:46,741]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 20:07:46,743]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 20:07:46,744]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 20:07:46,745]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 20:07:46,745]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 20:07:46,746]        sht1x:    **exit**:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 20:07:46,747]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'NameError'>
name 'temp' is not defined
<traceback object at 0x769d1d28>
[2015-02-17 20:08:11,860]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 20:08:11,861]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 20:08:11,862]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 20:08:11,863]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 20:08:11,864]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 20:08:11,865]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 20:08:11,866]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 20:08:11,866]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 20:08:11,867]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x769bfda0>
[2015-02-17 21:42:33,279]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 21:42:33,281]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 21:42:33,282]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 21:42:33,283]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 21:42:33,284]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 21:42:33,285]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 21:42:33,286]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 21:42:33,286]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 21:42:33,287]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x1c5ddf0>
[2015-02-17 21:48:44,019]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 21:48:44,020]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 21:48:44,021]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 21:48:44,022]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 21:48:44,023]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 21:48:44,024]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 21:48:44,024]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 21:48:44,025]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 21:48:44,026]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x1f52df0>
[2015-02-17 21:48:59,368]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 21:48:59,369]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 21:48:59,370]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 21:48:59,371]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 21:48:59,372]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 21:48:59,373]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 21:48:59,374]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 21:48:59,374]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 21:48:59,375]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x1155df0>
[2015-02-17 21:54:01,280]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 21:54:01,281]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 21:54:01,282]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 21:54:01,283]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 21:54:01,284]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 21:54:01,285]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 21:54:01,286]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 21:54:01,286]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 21:54:01,287]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x22f4df0>
[2015-02-17 21:56:19,672]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 21:56:19,674]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 21:56:19,674]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 21:56:19,675]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 21:56:19,676]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 21:56:19,677]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 21:56:19,678]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 21:56:19,678]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 21:56:19,679]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x13dfdf0>
[2015-02-17 22:06:27,621]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:06:27,623]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:06:27,624]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 22:06:27,624]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 22:06:27,625]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 22:06:27,626]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 22:06:27,627]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 22:06:27,628]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 22:06:27,628]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x1a0cdf0>
[2015-02-17 22:07:11,548]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:07:11,549]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:07:11,550]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 22:07:11,551]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 22:07:11,552]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 22:07:11,553]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 22:07:11,553]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 22:07:11,554]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 22:07:11,555]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x70ddf0>
[2015-02-17 22:29:12,918]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:29:12,921]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:29:12,922]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 22:29:12,923]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 22:29:12,923]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 11
Clock Pin: 7
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 22:29:12,924]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 22:29:12,925]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 22:29:12,926]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [11]: GPIO.IN
Clock pin [7]: GPIO.OUT
[2015-02-17 22:29:12,926]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x1096e68>
[2015-02-17 22:29:37,601]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:29:37,602]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:29:37,603]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['WriteStatusRegister'] - 00000110]
[2015-02-17 22:34:05,989]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:34:05,992]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:34:05,993]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['WriteStatusRegister'] - 00000110]
[2015-02-17 22:43:06,453]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:43:06,455]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:43:06,455]        sht1x:_write_status_register:455  INFO      Writing Status Register: 00000000
[2015-02-17 22:43:06,456]        sht1x:    _get_ack:393  INFO      Command WriteStatusRegister [00000110] acknowledged: 6
[2015-02-17 22:43:06,457]        sht1x:    __init__:83   INFO      Initial configuration:
Data Pin: 18
Clock Pin: 23
GPIO mode: GPIO.BCM
Vdd: 3.5
Resolution: High
Heater: False
OTP no reload: False
CRC check: True
[2015-02-17 22:43:06,458]        sht1x:    _get_ack:393  INFO      Command ['Temperature'] [00000011] acknowledged: 3
[2015-02-17 22:43:06,459]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['Temperature'] - 00000011]
[2015-02-17 22:43:06,460]        sht1x:    __exit__:91   INFO      GPIO channel function status:
Data pin [18]: GPIO.IN
Clock pin [23]: GPIO.OUT
[2015-02-17 22:43:06,460]        sht1x:    **exit**:94   ERROR     Exception in with block: <class 'pi_sht1x.sht1x.SHT1xError'>
SHT1x failed to properly receive command [['Temperature'] - 00000011]
<traceback object at 0x103cdf0>
[2015-02-17 22:45:19,665]        sht1x:initialize_sensor:156  INFO      Initializing sensor using bit mask: 00000000
[2015-02-17 22:45:19,666]        sht1x:    _get_ack:393  INFO      Command ['WriteStatusRegister'] [00000110] acknowledged: 6
[2015-02-17 22:45:19,667]        sht1x:    _get_ack:396  ERROR     SHT1x failed to properly receive command [['WriteStatusRegister'] - 00000110]

**Comment by drohm** [comment]
I took a brief look at the data sheet and the sensors are very similar.  I'm going to dig into this over the weekend and see what adjustments are necessary to add SHT7x support.  I'll give you an update afterwards.

**Comment by drohm** [comment]
I just got my SHT-75. I should be able to look into this some time this weekend.

**Comment by drohm** [comment]
Closing this. If I get time to look into the SHT7x series I'll reopen this ticket.
