### ISSUE TITLE
install Error

### ISSUE THREAD

**Issue by TechBitz-ops** [drohm/pi-sht1x#6]
**$ sudo python setup.py install** 
running install
running bdist_egg
running egg_info
writing requirements to pi_sht1x.egg-info/requires.txt
writing dependency_links to pi_sht1x.egg-info/dependency_links.txt
writing pi_sht1x.egg-info/PKG-INFO
writing top-level names to pi_sht1x.egg-info/top_level.txt
reading manifest file 'pi_sht1x.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
Traceback (most recent call last):
  File "setup.py", line 57, in <module>
    'hardware', 'driver', 'ic'
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3.5/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/bdist_egg.py", line 152, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 195, in run
    self.find_sources()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 222, in find_sources
    mm.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.read_template()
  File "/usr/lib/python3.5/distutils/command/sdist.py", line 309, in read_template
    line = template.readline()
  File "/usr/lib/python3.5/distutils/text_file.py", line 175, in readline
    line = self.file.readline()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)**

**Comment by drohm** [comment]
@syther05 Have you tried installing via pip like the instructions say to do?

**Comment by TechBitz-ops** [comment]
Yes, 
I have just tried a clean install of archlinux  on P3

installed;
    python
    python-setuptools 
    python-pip

then Run

```
# pip3 install pi-sht1x
Collecting pi-sht1x
  Downloading pi-sht1x-1.0.8.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pi_sht1x.egg-info
    writing requirements to pip-egg-info/pi_sht1x.egg-info/requires.txt
    writing top-level names to pip-egg-info/pi_sht1x.egg-info/top_level.txt
    writing pip-egg-info/pi_sht1x.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/pi_sht1x.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/pi_sht1x.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/pi_sht1x.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-oi5wa4a3/pi-sht1x/setup.py", line 56, in <module>
        'hardware', 'driver', 'ic'
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 195, in run
        self.find_sources()
      File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 222, in find_sources
        mm.run()
      File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 308, in run
        self.read_template()
      File "/usr/lib/python3.5/distutils/command/sdist.py", line 309, in read_template
        line = template.readline()
      File "/usr/lib/python3.5/distutils/text_file.py", line 175, in readline
        line = self.file.readline()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    **UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)**

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-oi5wa4a3/pi-sht1x/
```

**Comment by drohm** [comment]
@syther05 I apologize for the delay getting back, life getting in the way...

Can you try pip installing the attached development package to see if this will install for you?  Please let me know the outcome.

`pip3 install pi-sht1x-1.0.9b0.tar.gz`

[pi-sht1x-1.0.9b0.tar.gz](https://github.com/drohm/pi-sht1x/files/530796/pi-sht1x-1.0.9b0.tar.gz)

**Comment by TechBitz-ops** [comment]
@drohm Thank you, I appreciate your reply.

I downloaded the file, but still get this?

[alarm@alarmpi ~]$ **sudo pip3 install pi-sht1x-1.0.9b0.tar.gz**
[sudo] password for alarm: 
Processing ./pi-sht1x-1.0.9b0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/pi_sht1x.egg-info
    writing requirements to pip-egg-info/pi_sht1x.egg-info/requires.txt
    writing top-level names to pip-egg-info/pi_sht1x.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/pi_sht1x.egg-info/dependency_links.txt
    writing pip-egg-info/pi_sht1x.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/pi_sht1x.egg-info/SOURCES.txt'
    /usr/lib/python3.5/site-packages/setuptools/dist.py:331: UserWarning: Normalizing '1.0.9b' to '1.0.9b0'
      normalized_version,
    warning: manifest_maker: standard file '-c' not found

```
reading manifest file 'pip-egg-info/pi_sht1x.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-_88sszvr-build/setup.py", line 56, in <module>
    'hardware', 'driver', 'ic'
  File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 195, in run
    self.find_sources()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 222, in find_sources
    mm.run()
  File "/usr/lib/python3.5/site-packages/setuptools/command/egg_info.py", line 308, in run
    self.read_template()
  File "/usr/lib/python3.5/distutils/command/sdist.py", line 309, in read_template
    line = template.readline()
  File "/usr/lib/python3.5/distutils/text_file.py", line 175, in readline
    line = self.file.readline()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)

----------------------------------------
```

**Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-_88sszvr-build/**

**Comment by drohm** [comment]
Try this version:

[pi-sht1x-1.0.9rc0.tar.gz](https://github.com/drohm/pi-sht1x/files/533944/pi-sht1x-1.0.9rc0.tar.gz)

**Comment by TechBitz-ops** [comment]
Same error as before unfortunately .
Could there be any dependencies i'm missing?

I have a clean install of Archlinux running on a Pi3 B;
Linux alarmpi 4.4.22-1-ARCH #1 SMP Sat Sep 24 16:34:42 MDT 2016 armv7l GNU/Linux

pip3 is installed of course.

**Comment by drohm** [comment]
I'm looking into it still.  I haven't tried running Arch on my Pi3 before so it may well be a dependency, but I'm not 100% sure.  Check to see if python-dev is installed, and if not install it and try again.  I'll keep investigating in the meantime.

**Comment by prybintsev** [comment]
I've sent a pull request fixing the issue:
https://github.com/drohm/pi-sht1x/pull/13

**Comment by drohm** [comment]
Merged.
